<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Business operations – Introduction to Capital Modeling and Portfolio Management</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./030_CapitalAdequacy.html" rel="next">
<link href="./010_Introduction.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-01c78b5cd655e4cd89133cf59d535862.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-44a2bfbc4aea0d0866ad2a0ddca8a790.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<link rel="icon" href="./static/favicon.ico" type="image/x-icon">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="2&nbsp; Business operations – Introduction to Capital Modeling and Portfolio Management">
<meta property="og:description" content="">
<meta property="og:image" content="https://cmm.mynl.com/img/accounting-views.svg">
<meta property="og:site_name" content="Introduction to Capital Modeling and Portfolio Management">
<meta name="twitter:title" content="2&nbsp; Business operations – Introduction to Capital Modeling and Portfolio Management">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://cmm.mynl.com/img/accounting-views.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./020_BusinessOperations.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Business operations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Capital Modeling and Portfolio Management</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dedication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dedication</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./010_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./020_BusinessOperations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Business operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./030_CapitalAdequacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capital adequacy and sources of risk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./040_PricingAndAllocation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Pricing and allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./050_Applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Applications of pricing and allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./060_SelectingSRM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Selecting and calibrating an SRM</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./065_Evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Evaluating models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./070_AdvancedTopics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Advanced topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./080_Calculations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Calculations with <code>Aggregate</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./090_EndMatter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Appendices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliography</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">In this chapter:</h2>
   
  <ul>
  <li><a href="#sec-BO-General-Considerations" id="toc-sec-BO-General-Considerations" class="nav-link active" data-scroll-target="#sec-BO-General-Considerations"><span class="header-section-number">2.1</span> General considerations</a></li>
  <li><a href="#sec-BO-Units" id="toc-sec-BO-Units" class="nav-link" data-scroll-target="#sec-BO-Units"><span class="header-section-number">2.2</span> Units</a></li>
  <li><a href="#sec-BO-Reinsurance" id="toc-sec-BO-Reinsurance" class="nav-link" data-scroll-target="#sec-BO-Reinsurance"><span class="header-section-number">2.3</span> Reinsurance</a></li>
  <li><a href="#sec-BO-ESG" id="toc-sec-BO-ESG" class="nav-link" data-scroll-target="#sec-BO-ESG"><span class="header-section-number">2.4</span> Asset risk and Economic Scenario Generator</a></li>
  <li><a href="#sec-BO-Capital-Structure" id="toc-sec-BO-Capital-Structure" class="nav-link" data-scroll-target="#sec-BO-Capital-Structure"><span class="header-section-number">2.5</span> Capital structure</a></li>
  <li><a href="#sec-BO-Accounting" id="toc-sec-BO-Accounting" class="nav-link" data-scroll-target="#sec-BO-Accounting"><span class="header-section-number">2.6</span> Accounting</a></li>
  <li><a href="#sec-BO-Pro-Forma" id="toc-sec-BO-Pro-Forma" class="nav-link" data-scroll-target="#sec-BO-Pro-Forma"><span class="header-section-number">2.7</span> Pro formas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-Business-Operations" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Business operations</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Remember that all models are wrong; the practical question is how wrong do they have to be to not be useful.</em><br>
<em>—George E. P. Box</em></p>
<section id="sec-BO-General-Considerations" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-BO-General-Considerations"><span class="header-section-number">2.1</span> General considerations</h2>
<p>Modeling the insurance business operations—in terms of cash flows and other accounting concepts—is the most significant part of capital modeling work. It would be impractical to try to explain this in detail here; multiple book volumes would be required. Indeed, much of the actuarial syllabus is devoted to knowledge that could be applied to this effort. Instead, this chapter offers an overview using a simple example and adds pointers into the existing literature.</p>
<p>After you have addressed the broad questions posed in <a href="010_Introduction.html#sec-Getting-Started" class="quarto-xref"><span>Section 1.3</span></a>, you will have to drill down into more specific design issues such as:</p>
<ul>
<li>Will the model be deterministic or stochastic?</li>
<li>What is the planning time horizon: one year versus an ongoing concern?</li>
<li>What is the calculation time horizon: one year versus to ultimate?</li>
<li>What is the time granularity: annual, quarterly, monthly, etc.?</li>
<li>Will it deal with the runoff of current business only, or will it model an ongoing concern?</li>
<li>How will it treat reserve risk?</li>
<li>How will it treat asset risk?</li>
<li>How will it treat investment income (risk-free rate, crediting, capital charge, simplifications from discounting)?</li>
<li>How will multiple related legal entities be reflected in the model?</li>
<li>What is the balance of variables between user-selected inputs (e.g., plan premium) and modeler-selected inputs (e.g., correlation or severity)?</li>
<li>What accounting and regulatory frameworks and constraints are supported (US Statutory, Solvency II, US GAAP, IFRS 17, rating agencies)?</li>
<li>How will the model relate to other corporate systems?</li>
</ul>
<p>See <span class="citation" data-cites="CASDFM">Emma et al. (<a href="references.html#ref-CASDFM" role="doc-biblioref">2000</a>)</span> chapter 4 for more some considerations on these dimensions of functionality; chapter 7 goes into more detail about outputs and reports. Chapter 5 presents a classification of risks:</p>
<ul>
<li>Asset risk (default, market value, liquidity)</li>
<li>Obligation risk (reserve, premium, loss projection, catastrophe, reinsurance, and expense)</li>
<li>Interest rate risk (asset, obligation, and net cash flows)</li>
<li>Mismanagement risk</li>
</ul>
<p>How deeply each is to be modeled is part of the requirements to be determined. <span class="citation" data-cites="CASDFM">Emma et al. (<a href="references.html#ref-CASDFM" role="doc-biblioref">2000</a>)</span> discusses the first three at length, but not the last.</p>
<p>Subsequent sections in this chapter elaborate on some of these issues.</p>
</section>
<section id="sec-BO-Units" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-BO-Units"><span class="header-section-number">2.2</span> Units</h2>
<p>Business operations start with the individual business units. These are the sources of premiums, losses, and some of the expenses. Expect to devote considerable effort to modeling losses; your loss model implementations will live in the Units module.</p>
<p>The design issues at this stage include:</p>
<ul>
<li>Granularity of represented components, i.e., breakdowns by geography, line of business, etc.</li>
<li>Granularity of frequency and severity assumptions.</li>
<li>Inclusion of parameter uncertainty, see <a href="070_AdvancedTopics.html#sec-Uncertainty" class="quarto-xref"><span>Section 8.1</span></a>.</li>
<li>Interactions among variables.</li>
<li>Feedback loops, i.e., embedded automatic conditional decisions. For example, future rate changes might be calculated based on emerging loss ratios.</li>
</ul>
<p>The existence of mismanagement risk (<a href="#sec-BO-General-Considerations" class="quarto-xref"><span>Section 2.1</span></a>) suggests that building in feedback loops—“management in a box”—might be too optimistic. We strongly recommend against trying to do this. Adjusting rates to follow inflation is reasonable because this is very likely to happen in reality. Adjusting rates on the basis of a previous random good or bad year is not reasonable because it is highly speculative as to what will happen in reality. Instead, have the model in effect state “if nothing is changed, this is what would likely happen next….”</p>
<p><span class="citation" data-cites="Daykin1993">Daykin et al. (<a href="references.html#ref-Daykin1993" role="doc-biblioref">1993</a>)</span> includes the following chapters relevant to the Units submodule:</p>
<ul>
<li>2 - Frequency</li>
<li>3 - Severity</li>
<li>4 - Compound distributions</li>
<li>5 - Simulation</li>
<li>9 - Extended time horizons, including reserves</li>
<li>10 - Premiums and markets</li>
<li>11 - Expenses</li>
<li>12 - Cycles and growth</li>
</ul>
<p><span class="citation" data-cites="Brehm2007">Brehm et al. (<a href="references.html#ref-Brehm2007" role="doc-biblioref">2007</a>)</span> includes:</p>
<ul>
<li>5.1 - Frequency and severity distributions</li>
<li>5.2, 5.3 - Reserves</li>
<li>5.5 - Underwriting cycles</li>
</ul>
<p>Nearly the entirety of <span class="citation" data-cites="KPW05">Klugman et al. (<a href="references.html#ref-KPW05" role="doc-biblioref">2019</a>)</span> is devoted to selecting, fitting, and applying mathematical models of losses.</p>
<p>If you are modeling reserves, you must accurately represent your own firm’s methodology. The literature on setting reserves is enormous, with <span class="citation" data-cites="friedland2010estimating">Friedland (<a href="references.html#ref-friedland2010estimating" role="doc-biblioref">2010</a>)</span> a good place to start. Seventeen text references on advanced reserving are listed at <span class="citation" data-cites="CAS2022text7">Casualty Actuarial Society (<a href="references.html#ref-CAS2022text7" role="doc-biblioref">2022</a>)</span>. <span class="citation" data-cites="Wuthrich2015">Wuthrich and Merz (<a href="references.html#ref-Wuthrich2015" role="doc-biblioref">2015</a>)</span> is a rich source of information on stochastic reserve models. <span class="citation" data-cites="CASHBK">Szkoda et al. (<a href="references.html#ref-CASHBK" role="doc-biblioref">1995</a>)</span> has a list of about 200 reserving considerations. <span class="citation" data-cites="ASOP43">Actuarial Standards Board (<a href="references.html#ref-ASOP43" role="doc-biblioref">2007</a>)</span> is also relevant.</p>
<p>Modeling the correlation between units’ loss experience can be particularly tricky. Reshuffling simulated loss outcomes to obtain a desired correlation matrix can be done by the Iman-Conover methods, see <a href="070_AdvancedTopics.html#sec-iman-conover" class="quarto-xref"><span>Section 8.2</span></a>.</p>
<p><span class="citation" data-cites="Aas2009">Aas et al. (<a href="references.html#ref-Aas2009" role="doc-biblioref">2009</a>)</span>, <span class="citation" data-cites="Embrechts2010b">Embrechts (<a href="references.html#ref-Embrechts2010b" role="doc-biblioref">2010</a>)</span>, and <span class="citation" data-cites="Brehm2007">Brehm et al. (<a href="references.html#ref-Brehm2007" role="doc-biblioref">2007</a>)</span> section 3.3 discuss copulas, which are mechanisms for introducing dependency that goes beyond simple correlation. For example, the routine loss bodies of two loss distributions can be uncorrelated while the high-loss tails become correlated.</p>
<p>Another technique for inducing dependence is the use of common causes. If there are underlying phenomena that influence losses in different units, then modeling those first, and the conditional distribution of unit losses second, can induce the desired dependence. This is most commonly seen in catastrophe modeling but can also appear in a technique called timeline simulation <span class="citation" data-cites="Brehm2007">(<a href="references.html#ref-Brehm2007" role="doc-biblioref">Brehm et al. 2007, sec. 3.4</a>)</span>, where specific events are modeled as occurring at specific points of time.</p>
<p>We now illustrate the workings of the Business Operations module with our InsCo example.</p>
<p>In a real engagement, we would start with historical data on exposures, premiums, and losses. They would be on-leveled to represent the current (or anticipated next accounting year) situation. Probabilistic models would be fit, and a simulated sample of future possible outcomes generated. This work is covered early in the actuarial exam syllabus, and we imagine it has already been done.</p>
<p>InsCo has units <span class="math inline">\(i=1,\dots,m=3\)</span>, called A, B, and C. We represent their random experience <span class="math inline">\(X^i\)</span> by a table consisting of 10 outcomes with equal probabilities <span class="math inline">\(p_j=1/10\)</span>, <span class="math inline">\(j=1,\dots,n=10\)</span> with components <span class="math inline">\(X_j^i\)</span> and portfolio totals <span class="math inline">\(X_j\)</span>. The exact assumptions are detailed in <a href="#tbl-dupe-x" class="quarto-xref">Table&nbsp;<span>2.1</span></a>.</p>
<!--

| **Event** $j$ | **Unit A** $X_j^1$ | **Unit B** $X_j^2$ | **Unit C** $X_j^3$ | **Total** $X_j$ |
|:-------------:|-------------------:|-------------------:|-------------------:|----------------:|
|             1 |                 15 |                  7 |                  0 |              22 |
|             2 |                 15 |                 13 |                  0 |              28 |
|             3 |                  5 |                 20 |                 11 |              36 |
|             4 |                  7 |                 33 |                  0 |              40 |
|             5 |                 13 |                 20 |                  7 |              40 |
|             6 |                  5 |                 27 |                  8 |              40 |
|             7 |                 15 |                 16 |                  9 |              40 |
|             8 |                 26 |                 19 |                 10 |              55 |
|             9 |                 17 |                  8 |                 40 |              65 |
|            10 |                 16 |                 20 |                 64 |             100 |
|          E[X] |               13.4 |               18.3 |               14.9 |            46.6 |
|     Plan Prem |               13.9 |               18.7 |               19.6 |            52.2 |

-->
<div class="cell" data-execution_count="3">
<div id="tbl-dupe-x" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dupe-x-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: InsCo loss probability mass function by unit with expected loss, CV loss, and plan premium.
</figcaption>
<div aria-describedby="tbl-dupe-x-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div class="greater-table">
<style>
    #TASQP6IAFMUDJ  {
    border-collapse: collapse;
    font-family: "Roboto", "Open Sans Condensed", "Arial", 'Segoe UI', sans-serif;
    font-size: 1.0em;
    width: auto;
    
    margin: 10px auto;
    border: none;
    overflow: auto;
    margin-left: auto;
    margin-right: auto;
    }
    
    
    
    #TASQP6IAFMUDJ caption {
        padding: 4px 10px 2px 10px;
        font-size: 1.1em;
        text-align: center;
        font-weight: normal;
        caption-side: top;
    }
    #TASQP6IAFMUDJ thead {
        
        border-top: 1px solid #000;
        border-bottom: 1px solid #000;
        font-size: 1.0em;
        }
    #TASQP6IAFMUDJ tbody {
        
        border-bottom: 1px solid #000;
        }
    #TASQP6IAFMUDJ th  {
        vertical-align: bottom;
        padding: 4px 10px 4px 10px;
    }
    #TASQP6IAFMUDJ td {
        
        padding: 2px 10px 2px 10px;
        vertical-align: top;
    }
    
    #TASQP6IAFMUDJ .grt-hrule-0 {
        border-top: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-hrule-1 {
        border-top: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-hrule-2 {
        border-top: 0.0px solid #000;
    }
    
    #TASQP6IAFMUDJ .grt-bhrule-0 {
        border-bottom: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-bhrule-1 {
        border-bottom: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-vrule-index {
        border-left: 1px solid #000;
    }
    #TASQP6IAFMUDJ .grt-vrule-0 {
        border-left: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-vrule-1 {
        border-left: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-vrule-2 {
        border-left: 0.0px solid #000;
    }
    #TASQP6IAFMUDJ .grt-left {
        text-align: left;
    }
    #TASQP6IAFMUDJ .grt-center {
        text-align: center;
    }
    #TASQP6IAFMUDJ .grt-right {
        text-align: right;
        font-variant-numeric: tabular-nums;
    }
    #TASQP6IAFMUDJ .grt-head {
        font-family: "Times New Roman", 'Courier New';
        font-size: 1.0em;
    }
    #TASQP6IAFMUDJ .grt-bold {
        font-weight: bold;
    }

</style>

<table id="TASQP6IAFMUDJ" class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th class="grt-left" data-quarto-table-cell-role="th">Event \(j\)</th>
<th class="grt-center grt-vrule-index" data-quarto-table-cell-role="th">Unit A \(X^1_j\)</th>
<th class="grt-center grt-vrule-0" data-quarto-table-cell-role="th">Unit B \(X^2_j\)</th>
<th class="grt-center grt-vrule-0" data-quarto-table-cell-role="th">Unit C \(X^3_j\)</th>
<th class="grt-center grt-vrule-0" data-quarto-table-cell-role="th">Total \(X_j\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="grt-c-0 grt-left">1</td>
<td class="grt-c-1 grt-right grt-vrule-index">15</td>
<td class="grt-c-2 grt-right grt-vrule-0">7</td>
<td class="grt-c-3 grt-right grt-vrule-0">0</td>
<td class="grt-c-4 grt-right grt-vrule-0">22</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">2</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">15</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">13</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">0</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">28</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">3</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">5</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">20</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">11</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">36</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">4</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">7</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">33</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">0</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">40</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">5</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">13</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">20</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">7</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">40</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">6</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">5</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">27</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">8</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">40</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">7</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">15</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">16</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">9</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">40</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">8</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">26</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">19</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">10</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">55</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">9</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">17</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">8</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">40</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">65</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">10</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">16</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">20</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">64</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">100</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">EX</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">13.4</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">18.3</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">14.9</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">46.6</td>
</tr>
<tr class="even">
<td class="grt-c-0 grt-left grt-hrule-0">CV</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">0.453</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">0.412</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">1.324</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">0.455</td>
</tr>
<tr class="odd">
<td class="grt-c-0 grt-left grt-hrule-0">Plan Prem</td>
<td class="grt-c-1 grt-right grt-hrule-0 grt-vrule-index">13.9</td>
<td class="grt-c-2 grt-right grt-hrule-0 grt-vrule-0">18.7</td>
<td class="grt-c-3 grt-right grt-hrule-0 grt-vrule-0">19.6</td>
<td class="grt-c-4 grt-right grt-hrule-0 grt-vrule-0">52.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>There is some correlation among the simulated experience of the units. This correlation might have been imposed by a sampling technique involving copulas, but here we simply present the results. <a href="#tbl-dupe-x" class="quarto-xref">Table&nbsp;<span>2.1</span></a> represents the loss portion of the Unit module. Statisticians would call this table a discrete joint distribution, sample, or empirical distribution. Cat modelers might call it a <strong>probabilistic database</strong>. It shows expected loss for the portfolio is 46.6, plan premium is 52.2, and hence plan profit, or margin, is 5.6.</p>
</section>
<section id="sec-BO-Reinsurance" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-BO-Reinsurance"><span class="header-section-number">2.3</span> Reinsurance</h2>
<p>Assumed reinsurance, i.e., selling reinsurance or retrocessional cover to other insurance companies, should be treated as another unit, like homeowners or auto. Ceded reinsurance can be treated in one of two ways.</p>
<p>The simplest way is to treat reinsurance as a negative unit in parallel with the underlying unit. The premiums it receives are booked as negative (because they are really paid), and the losses it pays are booked as negative (because they are really received). For example, say there is the homeowners line of business being protected with catastrophe reinsurance. Then, the homeowners gross premiums and losses are posted to one unit and the reinsurance ceded premiums and ceded losses are posted as negatives to a parallel ceded homeowners unit. The algebraic sum of premiums (respectively, losses) constitute the net homeowners position which is not explicitly represented.</p>
<p>The more complicated way, and that implied by the design presented in <a href="010_Introduction.html#sec-System-Overview" class="quarto-xref"><span>Section 1.5</span></a>, is to have the operation of reinsurance modeled downstream of the units. This is recommended because there are many situations, such as corporate catastrophe covers, which impact multiple units.</p>
<p>In the end, it is simply a computational design choice about where calculations occur. Mathematically, the same gross-to-net transformation is being modeled either way.</p>
<p>The capital modeler may encounter two different types of reinsurance. The first is that purchased by business units. It is often reasonable for the corporate modeler to work with distributions net of this reinsurance, at least initially—business units typically frown on corporate modelers criticizing their reinsurance decisions! The second is reinsurance purchased at the corporate level that covers a number of different business units. Catastrophe reinsurance is typically of this form. Optimizing the purchase of catastrophe reinsurance (and allocating its cost to business units) is a wonderful application of capital models, and corporate purchases should usually be modeled explicitly to facilitate it.</p>
<p>Counterparty credit risk should be handled by representing the probabilistic nature of ceded losses. What is supposed to be received as a reinsurance payout may or may not actually occur. <span class="citation" data-cites="Brehm2007">Brehm et al. (<a href="references.html#ref-Brehm2007" role="doc-biblioref">2007</a>)</span> chapter 6.1 is devoted to reinsurance receivables as a risk class.</p>
<p>Our InsCo example includes a 35 excess of 65 portfolio stop-loss contract with ceded losses of 35 occurring only in event 10. There is no counterparty risk. This example is discussed in <a href="050_Applications.html#sec-Reinsurance-decision-making" class="quarto-xref"><span>Section 5.2</span></a>.</p>
</section>
<section id="sec-BO-ESG" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-BO-ESG"><span class="header-section-number">2.4</span> Asset risk and Economic Scenario Generator</h2>
<p>While the primary focus of the capital model is on how <em>insurance</em> liabilities impact the profitability and solvency of the firm, it may be desirable to represent contingencies on the asset side. First, to model assets as another source of volatility in the firm’s financial position, and, second, to model how macroeconomic phenomena impact the insurance liabilities themselves. The key to modeling asset risk is a module that simulates interest rates and returns on various asset classes and possibly unemployment, inflation, and other socioeconomic indices. Such a module is generally referred to as an <strong>Economic Scenario Generator</strong>.</p>
<p><span class="citation" data-cites="Brehm2007">Brehm et al. (<a href="references.html#ref-Brehm2007" role="doc-biblioref">2007</a>)</span> chapter 6.2 is devoted to investments. <span class="citation" data-cites="Daykin1993">Daykin et al. (<a href="references.html#ref-Daykin1993" role="doc-biblioref">1993</a>)</span> chapter 7 deals with inflation and chapter 8 is devoted to investments and asset/liability considerations such as the dynamics of reinvestment. <span class="citation" data-cites="conning2020ESG">Conning (<a href="references.html#ref-conning2020ESG" role="doc-biblioref">2020</a>)</span> provides a comprehensive “basic guide to Economic Scenario Generators, with an emphasis on applications for the property/casualty insurance industry.” Also note that the American Academy of Actuaries and the Society of Actuaries (SOA) have joined resources to manage the Economic Scenario Generators used in regulatory reserve and capital calculations <span class="citation" data-cites="SOA2024ESG">(<a href="references.html#ref-SOA2024ESG" role="doc-biblioref">Society of Actuaries 2024</a>)</span>. We are not using an Economic Scenario Generator in the InsCo example.</p>
</section>
<section id="sec-BO-Capital-Structure" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-BO-Capital-Structure"><span class="header-section-number">2.5</span> Capital structure</h2>
<p><strong>Capital structure</strong>, in corporate finance, refers to the division of liabilities corresponding to the sources of funds used to finance the firm. The basic division consists of shareholders’ equity, (possibly) preferred stock, various types of debt, and possibly other liabilities. Reinsurance can also be considered part of the capital structure. See <span class="citation" data-cites="PIR">Mildenhall and Major (<a href="references.html#ref-PIR" role="doc-biblioref">2022</a>)</span> for more on this perspective.</p>
<p>An important aspect of capital structure is its hierarchical nature insofar as there exists a pecking order in which the claimants providing these funds must be repaid in the course of liquidation. Insureds, providing premiums, come first. Common stockholders come last.</p>
<p>For an insurance entity, capital refers to the excess of assets over policyholder liabilities, whereas equity refers to the excess of assets over all other liabilities. Thus, debt can count as capital but not equity. For example, InsCo’s assets consist of cash in the amount <span class="math inline">\(a=100\)</span>. The corresponding liabilities—the capital structure—consist of unearned premiums, a bond that InsCo had issued in the past and upon which it must pay a 3% annual coupon, and shareholder equity. See <a href="#tbl-t0-bal-sheet" class="quarto-xref">Table&nbsp;<span>2.2</span></a>.</p>
<p>In the analysis presented in this monograph, it is usually sufficient to distinguish premiums <span class="math inline">\(P\)</span> from capital <span class="math inline">\(Q\)</span> (but adhere to <a href="010_Introduction.html#eq-funding" class="quarto-xref">Equation&nbsp;<span>1.1</span></a>). However, it may be desirable to distinguish components of <span class="math inline">\(Q\)</span> in reporting the financial fortunes of the firm. The hierarchy of claimants induces thresholds or benchmarks to distinguish degrees of financial distress or insolvency. This is elaborated upon in <a href="030_CapitalAdequacy.html" class="quarto-xref"><span>Chapter 3</span></a>.</p>
</section>
<section id="sec-BO-Accounting" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="sec-BO-Accounting"><span class="header-section-number">2.6</span> Accounting</h2>
<p>Accounting is the language of business that defines the measurement of success or failure. It has its own vocabulary and grammar. You must have someone well versed in insurance accounting on the model development team. Whatever underlying representation for business cash flows the model uses must be translated into one or more standard accounting frameworks. This is material covered in the Casualty Actuarial Society’s Exam 6. A good place to start is the detailed reading by <span class="citation" data-cites="Odomirok2013a">Odomirok et al. (<a href="references.html#ref-Odomirok2013a" role="doc-biblioref">2020</a>)</span> or the earlier short introduction by <span class="citation" data-cites="Ralph2008">Blanchard III (<a href="references.html#ref-Ralph2008" role="doc-biblioref">2008</a>)</span>.</p>
<p>Accounting is important for several reasons.</p>
<p>First, model output must be readily integrated with the firm’s business plan. The plan is the key document orienting the goals of the company. The capital model is intended to express and quantify the possible future variations from the plan that may emerge. In order to be useful and readily communicated to a variety of business actors in the firm, the model output needs to be expressed in the same terms as, and in a comparable format to, the plan. Companies often use their own management accounting conventions, usually slight variations on their reporting or regulatory standards. Therefore, the outputs must hew to the same accounting standards as the plan.</p>
<p>Second, accounting has real-world consequences. Insurers are subject to various types of valuation accounting standards, including:</p>
<ol type="1">
<li>Statutory or regulatory standards, such as US NAIC, EU Solvency II, APRA.</li>
<li>Financial reporting standards, such as GAAP and IFRS.</li>
<li>Rating agency standards, such as Standard and Poor’s and AM Best’s.</li>
</ol>
<p>Failure to maintain an adequate financial position under any one of these standards could prove ruinous to the firm. This is elaborated on in <span class="citation" data-cites="PIR">Mildenhall and Major (<a href="references.html#ref-PIR" role="doc-biblioref">2022</a>)</span>, section 8.3.</p>
<p><span class="citation" data-cites="CASDFM">Emma et al. (<a href="references.html#ref-CASDFM" role="doc-biblioref">2000</a>)</span> chapter 7 opines that models should simultaneously represent at least cash (economic), statutory, reporting (GAAP, IFRS17), and tax accounting because “[t]his is the only way to reflect the details of the interrelationships among constraints.” The model must model cash flows, which form the basis for the other accrual accounting models. In addition to representing external reporting standards, it is advisable to support your entity’s management accounting, which is usually a slight variant of its reporting standard.</p>
<p><a href="#fig-Accounting" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> illustrates the relationship between three accounting views. For example, reserves are undiscounted under US GAAP and the market view of loss reserves may differ from management’s.</p>
<div id="fig-Accounting" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Accounting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="img/accounting-views.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;2.1: Capital, surplus, and equity under market value, GAAP, and statutory accounting views. From @PIR, used by permission."><img src="img/accounting-views.svg" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Accounting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Capital, surplus, and equity under market value, GAAP, and statutory accounting views. From <span class="citation" data-cites="PIR">Mildenhall and Major (<a href="references.html#ref-PIR" role="doc-biblioref">2022</a>)</span>, used by permission.
</figcaption>
</figure>
</div>
<p>Accounting produces income and balance sheet statements. The InsCo beginning period <span class="math inline">\(t=0\)</span> balance sheet is shown in <a href="#tbl-t0-bal-sheet" class="quarto-xref">Table&nbsp;<span>2.2</span></a>. Recall that the total plan premium is 52.2, received at the beginning of the policy period; expenses are excluded from this model and are assumed to be zero.</p>
<div id="tbl-t0-bal-sheet" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-t0-bal-sheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: InsCo’s starting balance sheet.
</figcaption>
<div aria-describedby="tbl-t0-bal-sheet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Assets</strong></th>
<th style="text-align: right;"></th>
<th style="text-align: left;"><strong>Liabilities</strong></th>
<th style="text-align: right;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cash</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: left;">Unearned premium reserve</td>
<td style="text-align: right;">52.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Debt (bond)</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Shareholder equity</td>
<td style="text-align: right;">27.8</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-BO-Pro-Forma" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="sec-BO-Pro-Forma"><span class="header-section-number">2.7</span> Pro formas</h2>
<p><strong>Pro forma financial statements</strong> are hypothetical financial statements about future states of the business. Whatever internal representation the model uses for outcomes, they must be translated into standard fiancial reports. We focus here on InsCo’s balance sheet and income statements. Others are possible, including:</p>
<ul>
<li>Cash flow</li>
<li>Sources and uses of funds</li>
<li>Change in equity</li>
<li>Comprehensive income</li>
<li>Various statutory blanks, NAIC annual statement</li>
</ul>
<p>For our one-period InsCo, the ending period shareholder value, if positive, is released to investors at time <span class="math inline">\(t=1\)</span>. For event 4 in <a href="#tbl-dupe-x" class="quarto-xref">Table&nbsp;<span>2.1</span></a>, the income statement and balance sheet prior to paying losses and dividends are shown in <a href="#tbl-inc-stmt-4" class="quarto-xref">Table&nbsp;<span>2.3</span></a> and <a href="#tbl-t1-bal-sheet-4" class="quarto-xref">Table&nbsp;<span>2.4</span></a>. The balance sheet after payments is obviously <span class="math inline">\(0=0\)</span> because InsCo is a one-period entity.</p>
<div id="tbl-inc-stmt-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-inc-stmt-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: InsCo income statement, event 4.
</figcaption>
<div aria-describedby="tbl-inc-stmt-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Income</strong></th>
<th style="text-align: right;"></th>
<th style="text-align: left;"><strong>Expense</strong></th>
<th style="text-align: right;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Premiums</td>
<td style="text-align: right;">52.2</td>
<td style="text-align: left;">Loss &amp; LAE</td>
<td style="text-align: right;">40.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Bond coupon</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Shareholder dividends</td>
<td style="text-align: right;">11.6</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-t1-bal-sheet-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-t1-bal-sheet-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: InsCo ending balance sheet, event 4 prior to paying losses.
</figcaption>
<div aria-describedby="tbl-t1-bal-sheet-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Assets</strong></th>
<th style="text-align: right;"></th>
<th style="text-align: left;"><strong>Liabilities</strong></th>
<th style="text-align: right;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cash</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: left;">Unearned premium reserve</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Loss reserves</td>
<td style="text-align: right;">40.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Debt (bond)</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Accrued interest</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Shareholder equity</td>
<td style="text-align: right;">39.4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The Accounting module would produce 10 such pairs of financial statements.</p>
<p>Statutory reporting, done to satisfy regulatory authorities, is a deep and complex subject. Actuaries operating in the US should be familiar with the NAIC procedures manuals that can be found in Appendix V of <span class="citation" data-cites="COPLFR2023">Koca et al. (<a href="references.html#ref-COPLFR2023" role="doc-biblioref">2023</a>)</span>.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Aas2009" class="csl-entry" role="listitem">
Aas, Kjersti, Claudia Czado, Arnoldo Frigessi, and Henrik Bakken. 2009. <span>“<span class="nocase">Pair-copula constructions of multiple dependence</span>.”</span> <em>Insurance: Mathematics and Economics</em> 44 (2): 182–98. <a href="https://doi.org/10.1016/j.insmatheco.2007.02.001">https://doi.org/10.1016/j.insmatheco.2007.02.001</a>.
</div>
<div id="ref-ASOP43" class="csl-entry" role="listitem">
Actuarial Standards Board. 2007. <span>“<span>Property/Casualty Unpaid Claim Estimates</span>.”</span> <em>Actuarial Standard of Practice No. 43</em>.
</div>
<div id="ref-Ralph2008" class="csl-entry" role="listitem">
Blanchard III, Ralph S. 2008. <em><span>Basic Insurance Accounting – Selected Topics</span></em>. July.
</div>
<div id="ref-Brehm2007" class="csl-entry" role="listitem">
Brehm, Paul J, Spencer M Gluck, Kreps Rodney E, et al. 2007. <span>“Enterprise Risk Analysis for Property &amp; Liability Insurance Companies.”</span> <em>Guy Carpenter &amp; Company, LLC</em>.
</div>
<div id="ref-CAS2022text7" class="csl-entry" role="listitem">
Casualty Actuarial Society. 2022. <em><span class="nocase">Complete Text References for Exam 7, Syllabus of Basic Education</span></em>. <a href="https://www.casact.org/sites/default/files/2021-03/7_individual_textref.pdf">https://www.casact.org/sites/default/files/2021-03/7_individual_textref.pdf</a>.
</div>
<div id="ref-conning2020ESG" class="csl-entry" role="listitem">
Conning. 2020. <span>“A User’s Guide to Economic Scenario Generation in Property/Casualty Insurance.”</span> <em>CAS Research Papers</em>. <a href="https://www.casact.org/sites/default/files/2021-02/economic-scenario-generation-conning1020.pdf">https://www.casact.org/sites/default/files/2021-02/economic-scenario-generation-conning1020.pdf</a>.
</div>
<div id="ref-Daykin1993" class="csl-entry" role="listitem">
Daykin, Chris D, Teivo Pentikainen, and Martti Pesonen. 1993. <em>Practical Risk Theory for Actuaries</em>. Chapman; Hall/CRC.
</div>
<div id="ref-Embrechts2010b" class="csl-entry" role="listitem">
Embrechts, Paul. 2010. <span>“<span class="nocase">Risk Aggregation presentation</span>.”</span> <em>Copula Theory and Its Applications</em>, 111–26. <a href="https://doi.org/10.1007/978-3-642-12465-5">https://doi.org/10.1007/978-3-642-12465-5</a>.
</div>
<div id="ref-CASDFM" class="csl-entry" role="listitem">
Emma, Charles C et al. 2000. <em>Dynamic Financial Models of Property-Casualty Insurers</em>. Casualty Actuarial Society. <a href="https://www.casact.org/sites/default/files/database/forum_00wforum_00wf317.pdf">https://www.casact.org/sites/default/files/database/forum_00wforum_00wf317.pdf</a>.
</div>
<div id="ref-friedland2010estimating" class="csl-entry" role="listitem">
Friedland, Jacqueline. 2010. <span>“Estimating Unpaid Claims Using Basic Techniques.”</span> <a href="https://www.casact.org/sites/default/files/database/studynotes_friedland_estimating.pdf">https://www.casact.org/sites/default/files/database/studynotes_friedland_estimating.pdf</a>.
</div>
<div id="ref-KPW05" class="csl-entry" role="listitem">
Klugman, Stuart A, Harry H Panjer, and Gordon E Willmot. 2019. <em>Loss Models: From Data to Decisions</em>. Vol. 715. John Wiley &amp; Sons.
</div>
<div id="ref-COPLFR2023" class="csl-entry" role="listitem">
Koca, Stephen et al. 2023. <em>Statements of Actuarial Opinion on Property and Casualty Loss Reserves</em>. American Academy of Actuaries.
</div>
<div id="ref-PIR" class="csl-entry" role="listitem">
Mildenhall, Stephen J, and John A Major. 2022. <em>Pricing Insurance Risk: Theory and Practice</em>. John Wiley &amp; Sons, Inc.
</div>
<div id="ref-Odomirok2013a" class="csl-entry" role="listitem">
Odomirok, Kathleen C, Liam M Mcfarlane, Gareth L Kennedy, and Justin J Brenden. 2020. <em><span class="nocase">Casualty Actuarial Society Financial Reporting through the Lens of a Property/Casualty Actuary</span></em>.
</div>
<div id="ref-SOA2024ESG" class="csl-entry" role="listitem">
Society of Actuaries. 2024. <em>Economic Scenario Generators|SOA</em>. <a href="https://www.soa.org/resources/tables-calcs-tools/research-scenario/">https://www.soa.org/resources/tables-calcs-tools/research-scenario/</a>.
</div>
<div id="ref-CASHBK" class="csl-entry" role="listitem">
Szkoda, Susan T et al. 1995. <em>CAS Dynamic Financial Analysis Property/Casualty Insurance Companies Handbook</em>. Casualty Actuarial Society. <a href="https://www.casact.org/sites/default/files/database/forum_96wforum_96wf001.pdf">https://www.casact.org/sites/default/files/database/forum_96wforum_96wf001.pdf</a>.
</div>
<div id="ref-Wuthrich2015" class="csl-entry" role="listitem">
Wuthrich, Mario V., and Michael Merz. 2015. <em><span class="nocase">Stochastic Claims Reserving Manual: Advances in Dynamic Modeling</span></em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/cmm\.mynl\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./010_Introduction.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./030_CapitalAdequacy.html" class="pagination-link" aria-label="Capital adequacy and sources of risk">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Capital adequacy and sources of risk</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu"># Business operations {#sec-Business-Operations}</span></span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a>*Remember that all models are wrong; the practical question is how wrong do they have to be to not be useful.*\</span>
<span id="cb1-4"><a href="#cb1-4"></a>*—George E. P. Box*</span>
<span id="cb1-5"><a href="#cb1-5"></a></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">## General considerations {#sec-BO-General-Considerations}</span></span>
<span id="cb1-7"><a href="#cb1-7"></a></span>
<span id="cb1-8"><a href="#cb1-8"></a>Modeling the insurance business operations—in terms of cash flows and other accounting concepts—is the most significant part of capital modeling work. It would be impractical to try to explain this in detail here; multiple book volumes would be required. Indeed, much of the actuarial syllabus is devoted to knowledge that could be applied to this effort. Instead, this chapter offers an overview using a simple example and adds pointers into the existing literature.</span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a>After you have addressed the broad questions posed in @sec-Getting-Started, you will have to drill down into more specific design issues such as:</span>
<span id="cb1-11"><a href="#cb1-11"></a></span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="ss">-   </span>Will the model be deterministic or stochastic?</span>
<span id="cb1-13"><a href="#cb1-13"></a><span class="ss">-   </span>What is the planning time horizon: one year versus an ongoing concern?</span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="ss">-   </span>What is the calculation time horizon: one year versus to ultimate?</span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="ss">-   </span>What is the time granularity: annual, quarterly, monthly, etc.?</span>
<span id="cb1-16"><a href="#cb1-16"></a><span class="ss">-   </span>Will it deal with the runoff of current business only, or will it model an ongoing concern?</span>
<span id="cb1-17"><a href="#cb1-17"></a><span class="ss">-   </span>How will it treat reserve risk?</span>
<span id="cb1-18"><a href="#cb1-18"></a><span class="ss">-   </span>How will it treat asset risk?</span>
<span id="cb1-19"><a href="#cb1-19"></a><span class="ss">-   </span>How will it treat investment income (risk-free rate, crediting, capital charge, simplifications from discounting)?</span>
<span id="cb1-20"><a href="#cb1-20"></a><span class="ss">-   </span>How will multiple related legal entities be reflected in the model?</span>
<span id="cb1-21"><a href="#cb1-21"></a><span class="ss">-   </span>What is the balance of variables between user-selected inputs (e.g., plan premium) and modeler-selected inputs (e.g., correlation or severity)?</span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="ss">-   </span>What accounting and regulatory frameworks and constraints are supported (US Statutory, Solvency II, US GAAP, IFRS 17, rating agencies)?</span>
<span id="cb1-23"><a href="#cb1-23"></a><span class="ss">-   </span>How will the model relate to other corporate systems?</span>
<span id="cb1-24"><a href="#cb1-24"></a></span>
<span id="cb1-25"><a href="#cb1-25"></a>See @CASDFM chapter 4 for more some considerations on these dimensions of functionality; chapter 7 goes into more detail about outputs and reports. Chapter 5 presents a classification of risks:</span>
<span id="cb1-26"><a href="#cb1-26"></a></span>
<span id="cb1-27"><a href="#cb1-27"></a><span class="ss">-   </span>Asset risk (default, market value, liquidity)</span>
<span id="cb1-28"><a href="#cb1-28"></a><span class="ss">-   </span>Obligation risk (reserve, premium, loss projection, catastrophe, reinsurance, and expense)</span>
<span id="cb1-29"><a href="#cb1-29"></a><span class="ss">-   </span>Interest rate risk (asset, obligation, and net cash flows)</span>
<span id="cb1-30"><a href="#cb1-30"></a><span class="ss">-   </span>Mismanagement risk</span>
<span id="cb1-31"><a href="#cb1-31"></a></span>
<span id="cb1-32"><a href="#cb1-32"></a>How deeply each is to be modeled is part of the requirements to be determined. @CASDFM discusses the first three at length, but not the last.</span>
<span id="cb1-33"><a href="#cb1-33"></a></span>
<span id="cb1-34"><a href="#cb1-34"></a>Subsequent sections in this chapter elaborate on some of these issues.</span>
<span id="cb1-35"><a href="#cb1-35"></a></span>
<span id="cb1-36"><a href="#cb1-36"></a><span class="fu">## Units {#sec-BO-Units}</span></span>
<span id="cb1-37"><a href="#cb1-37"></a></span>
<span id="cb1-38"><a href="#cb1-38"></a>Business operations start with the individual business units. These are the sources of premiums, losses, and some of the expenses. Expect to devote considerable effort to modeling losses; your loss model implementations will live in the Units module.</span>
<span id="cb1-39"><a href="#cb1-39"></a></span>
<span id="cb1-40"><a href="#cb1-40"></a>The design issues at this stage include:</span>
<span id="cb1-41"><a href="#cb1-41"></a></span>
<span id="cb1-42"><a href="#cb1-42"></a><span class="ss">-   </span>Granularity of represented components, i.e., breakdowns by geography, line of business, etc.</span>
<span id="cb1-43"><a href="#cb1-43"></a><span class="ss">-   </span>Granularity of frequency and severity assumptions.</span>
<span id="cb1-44"><a href="#cb1-44"></a><span class="ss">-   </span>Inclusion of parameter uncertainty, see @sec-Uncertainty.</span>
<span id="cb1-45"><a href="#cb1-45"></a><span class="ss">-   </span>Interactions among variables.</span>
<span id="cb1-46"><a href="#cb1-46"></a><span class="ss">-   </span>Feedback loops, i.e., embedded automatic conditional decisions. For example, future rate changes might be calculated based on emerging loss ratios.</span>
<span id="cb1-47"><a href="#cb1-47"></a></span>
<span id="cb1-48"><a href="#cb1-48"></a>The existence of mismanagement risk (@sec-BO-General-Considerations) suggests that building in feedback loops—"management in a box"—might be too optimistic. We strongly recommend against trying to do this. Adjusting rates to follow inflation is reasonable because this is very likely to happen in reality. Adjusting rates on the basis of a previous random good or bad year is not reasonable because it is highly speculative as to what will happen in reality. Instead, have the model in effect state "if nothing is changed, this is what would likely happen next…."</span>
<span id="cb1-49"><a href="#cb1-49"></a></span>
<span id="cb1-50"><a href="#cb1-50"></a>@Daykin1993 includes the following chapters relevant to the Units submodule:</span>
<span id="cb1-51"><a href="#cb1-51"></a></span>
<span id="cb1-52"><a href="#cb1-52"></a><span class="ss">-   </span>2 - Frequency</span>
<span id="cb1-53"><a href="#cb1-53"></a><span class="ss">-   </span>3 - Severity</span>
<span id="cb1-54"><a href="#cb1-54"></a><span class="ss">-   </span>4 - Compound distributions</span>
<span id="cb1-55"><a href="#cb1-55"></a><span class="ss">-   </span>5 - Simulation</span>
<span id="cb1-56"><a href="#cb1-56"></a><span class="ss">-   </span>9 - Extended time horizons, including reserves</span>
<span id="cb1-57"><a href="#cb1-57"></a><span class="ss">-   </span>10 - Premiums and markets</span>
<span id="cb1-58"><a href="#cb1-58"></a><span class="ss">-   </span>11 - Expenses</span>
<span id="cb1-59"><a href="#cb1-59"></a><span class="ss">-   </span>12 - Cycles and growth</span>
<span id="cb1-60"><a href="#cb1-60"></a></span>
<span id="cb1-61"><a href="#cb1-61"></a>@Brehm2007 includes:</span>
<span id="cb1-62"><a href="#cb1-62"></a></span>
<span id="cb1-63"><a href="#cb1-63"></a><span class="ss">-   </span>5.1 - Frequency and severity distributions</span>
<span id="cb1-64"><a href="#cb1-64"></a><span class="ss">-   </span>5.2, 5.3 - Reserves</span>
<span id="cb1-65"><a href="#cb1-65"></a><span class="ss">-   </span>5.5 - Underwriting cycles</span>
<span id="cb1-66"><a href="#cb1-66"></a></span>
<span id="cb1-67"><a href="#cb1-67"></a>Nearly the entirety of @KPW05 is devoted to selecting, fitting, and applying mathematical models of losses.</span>
<span id="cb1-68"><a href="#cb1-68"></a></span>
<span id="cb1-69"><a href="#cb1-69"></a>If you are modeling reserves, you must accurately represent your own firm's methodology. The literature on setting reserves is enormous, with @friedland2010estimating a good place to start. Seventeen text references on advanced reserving are listed at @CAS2022text7. @Wuthrich2015 is a rich source of information on stochastic reserve models. @CASHBK has a list of about 200 reserving considerations. @ASOP43 is also relevant.</span>
<span id="cb1-70"><a href="#cb1-70"></a></span>
<span id="cb1-71"><a href="#cb1-71"></a>Modeling the correlation between units' loss experience can be particularly tricky. Reshuffling simulated loss outcomes to obtain a desired correlation matrix can be done by the Iman-Conover methods, see @sec-iman-conover.</span>
<span id="cb1-72"><a href="#cb1-72"></a></span>
<span id="cb1-73"><a href="#cb1-73"></a>@Aas2009, @Embrechts2010b, and @Brehm2007 section 3.3 discuss copulas, which are mechanisms for introducing dependency that goes beyond simple correlation. For example, the routine loss bodies of two loss distributions can be uncorrelated while the high-loss tails become correlated.</span>
<span id="cb1-74"><a href="#cb1-74"></a></span>
<span id="cb1-75"><a href="#cb1-75"></a>Another technique for inducing dependence is the use of common causes. If there are underlying phenomena that influence losses in different units, then modeling those first, and the conditional distribution of unit losses second, can induce the desired dependence. This is most commonly seen in catastrophe modeling but can also appear in a technique called timeline simulation <span class="co">[</span><span class="ot">@Brehm2007 section 3.4</span><span class="co">]</span>, where specific events are modeled as occurring at specific points of time.</span>
<span id="cb1-76"><a href="#cb1-76"></a></span>
<span id="cb1-77"><a href="#cb1-77"></a>We now illustrate the workings of the Business Operations module with our InsCo example.</span>
<span id="cb1-78"><a href="#cb1-78"></a></span>
<span id="cb1-79"><a href="#cb1-79"></a>In a real engagement, we would start with historical data on exposures, premiums, and losses. They would be on-leveled to represent the current (or anticipated next accounting year) situation. Probabilistic models would be fit, and a simulated sample of future possible outcomes generated. This work is covered early in the actuarial exam syllabus, and we imagine it has already been done.</span>
<span id="cb1-80"><a href="#cb1-80"></a></span>
<span id="cb1-81"><a href="#cb1-81"></a>InsCo has units $i=1,\dots,m=3$, called A, B, and C. We represent their random experience $X^i$ by a table consisting of 10 outcomes with equal probabilities $p_j=1/10$, $j=1,\dots,n=10$ with components $X_j^i$ and portfolio totals $X_j$. The exact assumptions are detailed in @tbl-dupe-x.</span>
<span id="cb1-82"><a href="#cb1-82"></a></span>
<span id="cb1-83"><a href="#cb1-83"></a><span class="co">&lt;!--</span></span>
<span id="cb1-84"><a href="#cb1-84"></a></span>
<span id="cb1-85"><a href="#cb1-85"></a><span class="co">| **Event** $j$ | **Unit A** $X_j^1$ | **Unit B** $X_j^2$ | **Unit C** $X_j^3$ | **Total** $X_j$ |</span></span>
<span id="cb1-86"><a href="#cb1-86"></a><span class="co">|:-------------:|-------------------:|-------------------:|-------------------:|----------------:|</span></span>
<span id="cb1-87"><a href="#cb1-87"></a><span class="co">|             1 |                 15 |                  7 |                  0 |              22 |</span></span>
<span id="cb1-88"><a href="#cb1-88"></a><span class="co">|             2 |                 15 |                 13 |                  0 |              28 |</span></span>
<span id="cb1-89"><a href="#cb1-89"></a><span class="co">|             3 |                  5 |                 20 |                 11 |              36 |</span></span>
<span id="cb1-90"><a href="#cb1-90"></a><span class="co">|             4 |                  7 |                 33 |                  0 |              40 |</span></span>
<span id="cb1-91"><a href="#cb1-91"></a><span class="co">|             5 |                 13 |                 20 |                  7 |              40 |</span></span>
<span id="cb1-92"><a href="#cb1-92"></a><span class="co">|             6 |                  5 |                 27 |                  8 |              40 |</span></span>
<span id="cb1-93"><a href="#cb1-93"></a><span class="co">|             7 |                 15 |                 16 |                  9 |              40 |</span></span>
<span id="cb1-94"><a href="#cb1-94"></a><span class="co">|             8 |                 26 |                 19 |                 10 |              55 |</span></span>
<span id="cb1-95"><a href="#cb1-95"></a><span class="co">|             9 |                 17 |                  8 |                 40 |              65 |</span></span>
<span id="cb1-96"><a href="#cb1-96"></a><span class="co">|            10 |                 16 |                 20 |                 64 |             100 |</span></span>
<span id="cb1-97"><a href="#cb1-97"></a><span class="co">|          E[X] |               13.4 |               18.3 |               14.9 |            46.6 |</span></span>
<span id="cb1-98"><a href="#cb1-98"></a><span class="co">|     Plan Prem |               13.9 |               18.7 |               19.6 |            52.2 |</span></span>
<span id="cb1-99"><a href="#cb1-99"></a></span>
<span id="cb1-100"><a href="#cb1-100"></a><span class="co">--&gt;</span></span>
<span id="cb1-101"><a href="#cb1-101"></a></span>
<span id="cb1-104"><a href="#cb1-104"></a><span class="in">```{python}</span></span>
<span id="cb1-105"><a href="#cb1-105"></a><span class="co">#| echo: false</span></span>
<span id="cb1-106"><a href="#cb1-106"></a><span class="co">#| label: setup-020</span></span>
<span id="cb1-107"><a href="#cb1-107"></a><span class="op">%</span>run prefob.py</span>
<span id="cb1-108"><a href="#cb1-108"></a><span class="op">%</span>run <span class="op">-</span>i basic_example_script.py</span>
<span id="cb1-109"><a href="#cb1-109"></a><span class="in">```</span></span>
<span id="cb1-110"><a href="#cb1-110"></a></span>
<span id="cb1-113"><a href="#cb1-113"></a><span class="in">```{python}</span></span>
<span id="cb1-114"><a href="#cb1-114"></a><span class="co">#| echo: false</span></span>
<span id="cb1-115"><a href="#cb1-115"></a><span class="co">#| label: tbl-dupe-x</span></span>
<span id="cb1-116"><a href="#cb1-116"></a><span class="co">#| tbl-cap: "InsCo loss probability mass function by unit with expected loss, CV loss,  and plan premium."</span></span>
<span id="cb1-117"><a href="#cb1-117"></a>exhibits[<span class="st">'tbl-dupe-x'</span>]</span>
<span id="cb1-118"><a href="#cb1-118"></a><span class="in">```</span></span>
<span id="cb1-119"><a href="#cb1-119"></a></span>
<span id="cb1-120"><a href="#cb1-120"></a>There is some correlation among the simulated experience of the units. This correlation might have been imposed by a sampling technique involving copulas, but here we simply present the results. @tbl-dupe-x represents the loss portion of the Unit module. Statisticians would call this table a discrete joint distribution, sample, or empirical distribution. Cat modelers might call it a **probabilistic database**. It shows expected loss for the portfolio is 46.6, plan premium is 52.2, and hence plan profit, or margin, is 5.6.</span>
<span id="cb1-121"><a href="#cb1-121"></a></span>
<span id="cb1-122"><a href="#cb1-122"></a><span class="fu">## Reinsurance {#sec-BO-Reinsurance}</span></span>
<span id="cb1-123"><a href="#cb1-123"></a></span>
<span id="cb1-124"><a href="#cb1-124"></a>Assumed reinsurance, i.e., selling reinsurance or retrocessional cover to other insurance companies, should be treated as another unit, like homeowners or auto. Ceded reinsurance can be treated in one of two ways.</span>
<span id="cb1-125"><a href="#cb1-125"></a></span>
<span id="cb1-126"><a href="#cb1-126"></a>The simplest way is to treat reinsurance as a negative unit in parallel with the underlying unit. The premiums it receives are booked as negative (because they are really paid), and the losses it pays are booked as negative (because they are really received). For example, say there is the homeowners line of business being protected with catastrophe reinsurance. Then, the homeowners gross premiums and losses are posted to one unit and the reinsurance ceded premiums and ceded losses are posted as negatives to a parallel ceded homeowners unit. The algebraic sum of premiums (respectively, losses) constitute the net homeowners position which is not explicitly represented.</span>
<span id="cb1-127"><a href="#cb1-127"></a></span>
<span id="cb1-128"><a href="#cb1-128"></a>The more complicated way, and that implied by the design presented in @sec-System-Overview, is to have the operation of reinsurance modeled downstream of the units. This is recommended because there are many situations, such as corporate catastrophe covers, which impact multiple units.</span>
<span id="cb1-129"><a href="#cb1-129"></a></span>
<span id="cb1-130"><a href="#cb1-130"></a>In the end, it is simply a computational design choice about where calculations occur. Mathematically, the same gross-to-net transformation is being modeled either way.</span>
<span id="cb1-131"><a href="#cb1-131"></a></span>
<span id="cb1-132"><a href="#cb1-132"></a>The capital modeler may encounter two different types of reinsurance. The first is that purchased by business units. It is often reasonable for the corporate modeler to work with distributions net of this reinsurance, at least initially—business units typically frown on corporate modelers criticizing their reinsurance decisions! The second is reinsurance purchased at the corporate level that covers a number of different business units. Catastrophe reinsurance is typically of this form. Optimizing the purchase of catastrophe reinsurance (and allocating its cost to business units) is a wonderful application of capital models, and corporate purchases should usually be modeled explicitly to facilitate it.</span>
<span id="cb1-133"><a href="#cb1-133"></a></span>
<span id="cb1-134"><a href="#cb1-134"></a>Counterparty credit risk should be handled by representing the probabilistic nature of ceded losses. What is supposed to be received as a reinsurance payout may or may not actually occur. @Brehm2007 chapter 6.1 is devoted to reinsurance receivables as a risk class.</span>
<span id="cb1-135"><a href="#cb1-135"></a></span>
<span id="cb1-136"><a href="#cb1-136"></a>Our InsCo example includes a 35 excess of 65 portfolio stop-loss contract with ceded losses of 35 occurring only in event 10. There is no counterparty risk. This example is discussed in @sec-Reinsurance-decision-making.</span>
<span id="cb1-137"><a href="#cb1-137"></a></span>
<span id="cb1-138"><a href="#cb1-138"></a><span class="fu">## Asset risk and Economic Scenario Generator {#sec-BO-ESG}</span></span>
<span id="cb1-139"><a href="#cb1-139"></a></span>
<span id="cb1-140"><a href="#cb1-140"></a>While the primary focus of the capital model is on how *insurance* liabilities impact the profitability and solvency of the firm, it may be desirable to represent contingencies on the asset side. First, to model assets as another source of volatility in the firm's financial position, and, second, to model how macroeconomic phenomena impact the insurance liabilities themselves. The key to modeling asset risk is a module that simulates interest rates and returns on various asset classes and possibly unemployment, inflation, and other socioeconomic indices. Such a module is generally referred to as an **Economic Scenario Generator**.</span>
<span id="cb1-141"><a href="#cb1-141"></a></span>
<span id="cb1-142"><a href="#cb1-142"></a>@Brehm2007 chapter 6.2 is devoted to investments. @Daykin1993 chapter 7 deals with inflation and chapter 8 is devoted to investments and asset/liability considerations such as the dynamics of reinvestment. @conning2020ESG provides a comprehensive "basic guide to Economic Scenario Generators, with an emphasis on applications for the property/casualty insurance industry." Also note that the American Academy of Actuaries and the Society of Actuaries (SOA) have joined resources to manage the Economic Scenario Generators used in regulatory reserve and capital calculations <span class="co">[</span><span class="ot">@SOA2024ESG</span><span class="co">]</span>. We are not using an Economic Scenario Generator in the InsCo example.</span>
<span id="cb1-143"><a href="#cb1-143"></a></span>
<span id="cb1-144"><a href="#cb1-144"></a><span class="fu">## Capital structure {#sec-BO-Capital-Structure}</span></span>
<span id="cb1-145"><a href="#cb1-145"></a></span>
<span id="cb1-146"><a href="#cb1-146"></a>**Capital structure**, in corporate finance, refers to the division of liabilities corresponding to the sources of funds used to finance the firm. The basic division consists of shareholders' equity, (possibly) preferred stock, various types of debt, and possibly other liabilities. Reinsurance can also be considered part of the capital structure. See @PIR for more on this perspective.</span>
<span id="cb1-147"><a href="#cb1-147"></a></span>
<span id="cb1-148"><a href="#cb1-148"></a>An important aspect of capital structure is its hierarchical nature insofar as there exists a pecking order in which the claimants providing these funds must be repaid in the course of liquidation. Insureds, providing premiums, come first. Common stockholders come last.</span>
<span id="cb1-149"><a href="#cb1-149"></a></span>
<span id="cb1-150"><a href="#cb1-150"></a>For an insurance entity, capital refers to the excess of assets over policyholder liabilities, whereas equity refers to the excess of assets over all other liabilities. Thus, debt can count as capital but not equity. For example, InsCo's assets consist of cash in the amount $a=100$. The corresponding liabilities—the capital structure—consist of unearned premiums, a bond that InsCo had issued in the past and upon which it must pay a 3% annual coupon, and shareholder equity. See @tbl-t0-bal-sheet.</span>
<span id="cb1-151"><a href="#cb1-151"></a></span>
<span id="cb1-152"><a href="#cb1-152"></a>In the analysis presented in this monograph, it is usually sufficient to distinguish premiums $P$ from capital $Q$ (but adhere to @eq-funding). However, it may be desirable to distinguish components of $Q$ in reporting the financial fortunes of the firm. The hierarchy of claimants induces thresholds or benchmarks to distinguish degrees of financial distress or insolvency. This is elaborated upon in @sec-Capital-Adequacy.</span>
<span id="cb1-153"><a href="#cb1-153"></a></span>
<span id="cb1-154"><a href="#cb1-154"></a><span class="fu">## Accounting {#sec-BO-Accounting}</span></span>
<span id="cb1-155"><a href="#cb1-155"></a></span>
<span id="cb1-156"><a href="#cb1-156"></a>Accounting is the language of business that defines the measurement of success or failure. It has its own vocabulary and grammar. You must have someone well versed in insurance accounting on the model development team. Whatever underlying representation for business cash flows the model uses must be translated into one or more standard accounting frameworks. This is material covered in the Casualty Actuarial Society's Exam 6. A good place to start is the detailed reading by @Odomirok2013a or the earlier short introduction by @Ralph2008.</span>
<span id="cb1-157"><a href="#cb1-157"></a></span>
<span id="cb1-158"><a href="#cb1-158"></a>Accounting is important for several reasons.</span>
<span id="cb1-159"><a href="#cb1-159"></a></span>
<span id="cb1-160"><a href="#cb1-160"></a>First, model output must be readily integrated with the firm's business plan. The plan is the key document orienting the goals of the company. The capital model is intended to express and quantify the possible future variations from the plan that may emerge. In order to be useful and readily communicated to a variety of business actors in the firm, the model output needs to be expressed in the same terms as, and in a comparable format to, the plan. Companies often use their own management accounting conventions, usually slight variations on their reporting or regulatory standards. Therefore, the outputs must hew to the same accounting standards as the plan.</span>
<span id="cb1-161"><a href="#cb1-161"></a></span>
<span id="cb1-162"><a href="#cb1-162"></a>Second, accounting has real-world consequences. Insurers are subject to various types of valuation accounting standards, including:</span>
<span id="cb1-163"><a href="#cb1-163"></a></span>
<span id="cb1-164"><a href="#cb1-164"></a><span class="ss">1.  </span>Statutory or regulatory standards, such as US NAIC, EU Solvency II, APRA.</span>
<span id="cb1-165"><a href="#cb1-165"></a><span class="ss">2.  </span>Financial reporting standards, such as GAAP and IFRS.</span>
<span id="cb1-166"><a href="#cb1-166"></a><span class="ss">3.  </span>Rating agency standards, such as Standard and Poor’s and AM Best’s.</span>
<span id="cb1-167"><a href="#cb1-167"></a></span>
<span id="cb1-168"><a href="#cb1-168"></a>Failure to maintain an adequate financial position under any one of these standards could prove ruinous to the firm. This is elaborated on in @PIR, section 8.3.</span>
<span id="cb1-169"><a href="#cb1-169"></a></span>
<span id="cb1-170"><a href="#cb1-170"></a>@CASDFM chapter 7 opines that models should simultaneously represent at least cash (economic), statutory, reporting (GAAP, IFRS17), and tax accounting because "<span class="sc">\[</span>t<span class="sc">\]</span>his is the only way to reflect the details of the interrelationships among constraints." The model must model cash flows, which form the basis for the other accrual accounting models. In addition to representing external reporting standards, it is advisable to support your entity's management accounting, which is usually a slight variant of its reporting standard.</span>
<span id="cb1-171"><a href="#cb1-171"></a></span>
<span id="cb1-172"><a href="#cb1-172"></a>@fig-Accounting illustrates the relationship between three accounting views. For example, reserves are undiscounted under US GAAP and the market view of loss reserves may differ from management’s.</span>
<span id="cb1-173"><a href="#cb1-173"></a></span>
<span id="cb1-174"><a href="#cb1-174"></a><span class="al">![Capital, surplus, and equity under market value, GAAP, and statutory accounting views. From @PIR, used by permission.](img/accounting-views.svg)</span>{#fig-Accounting width="100%"}</span>
<span id="cb1-175"><a href="#cb1-175"></a></span>
<span id="cb1-176"><a href="#cb1-176"></a>Accounting produces income and balance sheet statements. The InsCo beginning period $t=0$ balance sheet is shown in @tbl-t0-bal-sheet. Recall that the total plan premium is 52.2, received at the beginning of the policy period; expenses are excluded from this model and are assumed to be zero.</span>
<span id="cb1-177"><a href="#cb1-177"></a></span>
<span id="cb1-178"><a href="#cb1-178"></a>| **Assets** |       | **Liabilities**          |      |</span>
<span id="cb1-179"><a href="#cb1-179"></a>|:-----------|------:|:-------------------------|-----:|</span>
<span id="cb1-180"><a href="#cb1-180"></a>| Cash       | 100.0 | Unearned premium reserve | 52.2 |</span>
<span id="cb1-181"><a href="#cb1-181"></a>|            |       | Debt (bond)              | 20.0 |</span>
<span id="cb1-182"><a href="#cb1-182"></a>|            |       | Shareholder equity       | 27.8 |</span>
<span id="cb1-183"><a href="#cb1-183"></a></span>
<span id="cb1-184"><a href="#cb1-184"></a>: InsCo's starting balance sheet. {#tbl-t0-bal-sheet}</span>
<span id="cb1-185"><a href="#cb1-185"></a></span>
<span id="cb1-186"><a href="#cb1-186"></a><span class="fu">## Pro formas {#sec-BO-Pro-Forma}</span></span>
<span id="cb1-187"><a href="#cb1-187"></a></span>
<span id="cb1-188"><a href="#cb1-188"></a>**Pro forma financial statements** are hypothetical financial statements about future states of the business. Whatever internal representation the model uses for outcomes, they must be translated into standard fiancial reports. We focus here on InsCo's balance sheet and income statements. Others are possible, including:</span>
<span id="cb1-189"><a href="#cb1-189"></a></span>
<span id="cb1-190"><a href="#cb1-190"></a><span class="ss">-   </span>Cash flow</span>
<span id="cb1-191"><a href="#cb1-191"></a><span class="ss">-   </span>Sources and uses of funds</span>
<span id="cb1-192"><a href="#cb1-192"></a><span class="ss">-   </span>Change in equity</span>
<span id="cb1-193"><a href="#cb1-193"></a><span class="ss">-   </span>Comprehensive income</span>
<span id="cb1-194"><a href="#cb1-194"></a><span class="ss">-   </span>Various statutory blanks, NAIC annual statement</span>
<span id="cb1-195"><a href="#cb1-195"></a></span>
<span id="cb1-196"><a href="#cb1-196"></a>For our one-period InsCo, the ending period shareholder value, if positive, is released to investors at time $t=1$. For event 4 in @tbl-dupe-x, the income statement and balance sheet prior to paying losses and dividends are shown in @tbl-inc-stmt-4 and @tbl-t1-bal-sheet-4. The balance sheet after payments is obviously $0=0$ because InsCo is a one-period entity.</span>
<span id="cb1-197"><a href="#cb1-197"></a></span>
<span id="cb1-198"><a href="#cb1-198"></a>| **Income** |      | **Expense**           |      |</span>
<span id="cb1-199"><a href="#cb1-199"></a>|:-----------|-----:|:----------------------|-----:|</span>
<span id="cb1-200"><a href="#cb1-200"></a>| Premiums   | 52.2 | Loss &amp; LAE            | 40.0 |</span>
<span id="cb1-201"><a href="#cb1-201"></a>|            |      | Bond coupon           |  0.6 |</span>
<span id="cb1-202"><a href="#cb1-202"></a>|            |      | Shareholder dividends | 11.6 |</span>
<span id="cb1-203"><a href="#cb1-203"></a></span>
<span id="cb1-204"><a href="#cb1-204"></a>: InsCo income statement, event 4. {#tbl-inc-stmt-4}</span>
<span id="cb1-205"><a href="#cb1-205"></a></span>
<span id="cb1-206"><a href="#cb1-206"></a>| **Assets** |       | **Liabilities**          |      |</span>
<span id="cb1-207"><a href="#cb1-207"></a>|:-----------|------:|:-------------------------|-----:|</span>
<span id="cb1-208"><a href="#cb1-208"></a>| Cash       | 100.0 | Unearned premium reserve |  0.0 |</span>
<span id="cb1-209"><a href="#cb1-209"></a>|            |       | Loss reserves            | 40.0 |</span>
<span id="cb1-210"><a href="#cb1-210"></a>|            |       | Debt (bond)              | 20.0 |</span>
<span id="cb1-211"><a href="#cb1-211"></a>|            |       | Accrued interest         |  0.6 |</span>
<span id="cb1-212"><a href="#cb1-212"></a>|            |       | Shareholder equity       | 39.4 |</span>
<span id="cb1-213"><a href="#cb1-213"></a></span>
<span id="cb1-214"><a href="#cb1-214"></a>: InsCo ending balance sheet, event 4 prior to paying losses. {#tbl-t1-bal-sheet-4}</span>
<span id="cb1-215"><a href="#cb1-215"></a></span>
<span id="cb1-216"><a href="#cb1-216"></a>The Accounting module would produce 10 such pairs of financial statements.</span>
<span id="cb1-217"><a href="#cb1-217"></a></span>
<span id="cb1-218"><a href="#cb1-218"></a>Statutory reporting, done to satisfy regulatory authorities, is a deep and complex subject. Actuaries operating in the US should be familiar with the NAIC procedures manuals that can be found in Appendix V of @COPLFR2023.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>DRAFT - do not redistribute</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>