---
appendix: true
---

# Appendices {#sec-Appendix}

## Table of symbols

\footnotesize

+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| **Symbol**             | **Interpretation**                                                      | **Reference**                                   |
+:=======================+:========================================================================+:================================================+
| $\alpha_k^i$           | unit $i$ share of layer $k$ expected loss                               | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\beta_k^i$            | unit $i$ share of layer $k$ premium                                     | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\delta$               | rate of discount, $\delta=\iota/(1+\iota)$                              | @sec-Pricing                                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\Delta X_k$           | layer $k$ limit, $\Delta X_k=X_{k+1}-X_k$                               | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\epsilon$             | scaling parameter                                                       | @sec-Risk-Analysis, @sec-portfolio-optimization |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\epsilon_-$           | minimum scale                                                           | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\epsilon_+$           | maximum scale                                                           | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\iota$                | expected return, cost of capital, $\iota = M/Q$                         | @sec-Pricing                                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\iota^i$              | unit $i$ cost of capital                                                | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\iota_k$              | layer $k$ cost of capital                                               | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\kappa^i(x)$          | unit $i$ conditional expected loss, $\kappa^i(x) := \mathsf E[X^i|X=x]$ | @sec-Complications                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\nabla^i\phi(X)$      | partial derivative with respect to scaling                              | @sec-Risk-Analysis                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\nu$                  | discount factor, $\nu=1/(1+\iota)$                                      | @sec-Pricing                                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\Phi(z)$              | standard Gaussian cumulative distribution function                      | @sec-5-distortions                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\rho()$               | pricing risk measure                                                    | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\theta$               | weight parameter for bi-TVaR                                            | @sec-envelope                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $a$                    | assets                                                                  | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $a()$                  | capital risk measure                                                    | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $a^i$                  | allocation of assets to unit $i$ (industry standard)                    | @sec-ISA                                        |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $g(s)$                 | distortion function                                                     | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $i$                    | index to portfolio unit                                                 | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $j$                    | event index, $j=1, \dots, n$                                            | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $k$                    | layer index, $k=0,\dots,n-1$                                            | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $L$                    | expected loss                                                           | @sec-Pricing                                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $L^i$                  | unit $i$ expected loss                                                  | @sec-ISA, @sec-pricing-units                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $M$                    | margin, $P=L+M$                                                         | @eq-PLM, @sec-Pricing                           |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $M^i$                  | unit $i$ margin $M^i = P^i - L^i$                                       | @sec-pricing-units                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $m$                    | number of units                                                         | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $n$                    | number of events                                                        | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $p_j$                  | event probability $p_j=\Pr(X=X_j)$                                      | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $P$                    | premium $P=\rho(X)$                                                     | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $P_k$                  | layer $k$ premium, $P_k = g(S_k)\Delta X_k$                             | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $P_P$                  | plan premium                                                            | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $P_R$                  | required premium                                                        | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $P^i$                  | unit $i$ premium                                                        | @sec-ISA, @sec-pricing-units                    |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $q_k$                  | distorted probability, $q_k = g(S_{k-1}) - g(S_{k})$                    | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $Q$                    | capital $Q=a-P$                                                         | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $Q^i$                  | unit $i$ capital                                                        | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $Q_k^i$                | unit $i$ capital in layer $k$                                           | @sec-Allocating-Capital                         |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $Q_P$                  | plan capital, $Q_P=a-P_P$                                               | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $r$                    | EVA/capital ratio, $r=V/Q_P$                                            | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $S_k$                  | layer $k$ attachment probability, $S_k=Pr(X > X_k)$                     | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\mathsf{TVaR}_{0.99}$ | InsCo example capital standard                                          | @sec-Risk-Analysis                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $V$                    | EVA, economic value added, $V=P_P-P_R$                                  | @sec-InsCo-opt                                  |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $\mathsf{VaR}_{0.85}$  | example alternative risk measure                                        | @sec-Risk-Analysis                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X$                    | portfolio liability random variable                                     | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X_0$                  | phantom portfolio loss $X_0=0$ with probability $p_0=0$                 | @sec-Complications                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X_j^i$                | loss to unit $i$ in event $j$                                           | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X_j$                  | portfolio loss in event $j$                                             | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X_k$                  | layer payout threshold (attachment)                                     | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X\wedge a$            | portfolio payout to policyholders                                       | @sec-Intro-Insco                                |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X^i(a)$               | unit $i$ capped losses                                                  | @sec-Complications                              |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $X^i$                  | loss to unit $i$ (random variable)                                      | @sec-BO-Units                                   |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+
| $Z_k$                  | event weight, likelihood ratio, $Z_k=q_k/p_k$                           | @sec-Pricing-layers                             |
+------------------------+-------------------------------------------------------------------------+-------------------------------------------------+

: Symbols used in this monograph. {#tbl-intro-symbols-alpha}

\normalsize

\clearpage

## Actuarial Standards of Practice {#sec-ASOPs}

"The Actuarial Standards Board (ASB) sets standards for appropriate actuarial practice in the United States through the development and promulgation of Actuarial Standards of Practice (ASOPs). These ASOPs describe the procedures an actuary should follow when performing actuarial services and identify what the actuary should disclose when communicating the results of those services." ASOPs can be found at https://www.actuarialstandardsboard.org/standards-of-practice/

\footnotesize

+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Number**  | **Title**                                                                                                        | **Reference**                                   |
+:===========:+:=================================================================================================================+=================================================+
| 7           | Analysis of Life, Health, or Property/Casualty Insurer Cash Flows                                                | @sec-Business-Operations                        |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 23          | Data Quality                                                                                                     | @sec-Business-Operations                        |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 30          | Treatment of Profit and Contingency Provisions and the Cost of Capital in Property/Casualty Insurance Ratemaking | @sec-Pricing-Allocation                         |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 46          | Risk Evaluation in Enterprise Risk Management                                                                    | @sec-Business-Operations, @sec-Capital-Adequacy |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 47          | Risk Treatment in Enterprise Risk Management                                                                     | @sec-Getting-Started, @sec-Risk-Analysis        |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 55          | Capital Adequacy Assessment                                                                                      | @sec-Capital-Adequacy                           |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 56          | Modeling                                                                                                         | @sec-Business-Operations                        |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+
| 58          | Enterprise Risk Management                                                                                       | @sec-Business-Operations, @sec-Capital-Adequacy |
+-------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------+

: ASOPs that are relevant to capital modeling. {#tbl-likely-ASOPs}

\normalsize

The ASB repealed ASOP Nos. 46 and 47 in December 2024 and replaced them with ASOP No. 58, Enterprise Risk Management, to reflect the developments since 2012, to better reflect today’s ERM practices and terminology, and to align with ASOP No. 55.

\footnotesize

+------------+--------------------------------------------------------------------------------------------------------------+
| **Number** | **Title**                                                                                                    |
+:==========:+:=============================================================================================================+
| 12         | Risk Classification (for All Practice Areas)                                                                 |
+------------+--------------------------------------------------------------------------------------------------------------+
| 13         | Trending Procedures in Property/Casualty Insurance                                                           |
+------------+--------------------------------------------------------------------------------------------------------------+
| 19         | Appraisals of Casualty, Health, and Life Insurance Businesses                                                |
+------------+--------------------------------------------------------------------------------------------------------------+
| 20         | Discounting of Property/Casualty Claim Estimates                                                             |
+------------+--------------------------------------------------------------------------------------------------------------+
| 25         | Credibility Procedures                                                                                       |
+------------+--------------------------------------------------------------------------------------------------------------+
| 29         | Expense Provisions for Prospective Property/Casualty Risk Transfer and Risk Retention                        |
+------------+--------------------------------------------------------------------------------------------------------------+
| 36         | Statements of Actuarial Opinion Regarding Property/Casualty Loss, Loss Adjustment Expense, or Other Reserves |
+------------+--------------------------------------------------------------------------------------------------------------+
| 38         | Catastrophe Modeling (for All Practice Areas)                                                                |
+------------+--------------------------------------------------------------------------------------------------------------+
| 39         | Treatment of Catastrophe Losses in Property/Casualty Insurance Ratemaking                                    |
+------------+--------------------------------------------------------------------------------------------------------------+
| 41         | Actuarial Communications                                                                                     |
+------------+--------------------------------------------------------------------------------------------------------------+
| 43         | Property/Casualty Unpaid Claim Estimates                                                                     |
+------------+--------------------------------------------------------------------------------------------------------------+
| 53         | Estimating Future Costs for Prospective Property/Casualty Risk Transfer and Risk Retention                   |
+------------+--------------------------------------------------------------------------------------------------------------+

: ASOPs that are potentially relevant to capital modeling. {#tbl-potential-ASOPs}

\normalsize

\clearpage

## Glossary

\footnotesize

+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Term**                            | **Description**                                                                                     | **Reference**                                   |
+:====================================+:====================================================================================================+:================================================+
| **Accounting**                      | module that produces financial statements                                                           | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Allocation**                      | module that distributes portfolio premium to units                                                  | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **BCAR**                            | Best's Capital Adequacy Ratio                                                                       | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Bi-TVaR**                         | convex combination of TVaRs                                                                         | @sec-Selecting-Calibrating                      |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Business Operations**             | module that deals with loss experience                                                              | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Capital**                         | owner-provided funds                                                                                | @sec-What-Into                                  |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Capital Adequacy**                | module dealing with risk and capital sufficiency                                                    | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Capital risk measure**            | rule relating liabilities to required assets                                                        | @sec-Intro-Insco                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Capital structure**               | mix of liabilities funding total assets                                                             | @sec-System-Overview, @sec-BO-Capital-Structure |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Charter**                         | formal document setting out the rationale                                                           | @sec-Structure-Monograph                        |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Co-TVaR**                         | conditional TVaR, Natural Allocation of TVaR                                                        | @sec-Risk-Analysis                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **co-XTVaR**                        | Conditional XTVaR                                                                                   | @sec-ISA                                        |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Comonotonic**                     | Random variables $X$ and $Y$ are comonotonic if they are nondecreasing functions of a third r.v.    | @sec-Pricing-Allocation                         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Comonotonic additive**            | Property of a risk measure $\rho$: If $X$ and $Y$ are comonotonic, then $\rho(X+Y)=\rho(X)+\rho(Y)$ | @sec-Pricing-Allocation                         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Constant cost of capital (CCoC)** | assumption that all layers require the same return                                                  | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Distortion function**             | translates attachment probability to rate on line                                                   | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Distorted expectation**           | expectation calculated with distorted probabilities $q$                                             | @sec-pricing-units, @sec-pricing-events         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Distorted expected loss share**   | a unit's share of a layer's distorted expected loss, $\beta_k^i$                                    | @sec-Allocating-Capital                         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Distorted probability**           | after applying a distortion function, $q$ replaces $p$                                              | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Economic Scenario Generator**     | module to generate socioeconomic outcomes                                                           | @sec-System-Overview, @sec-BO-ESG               |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Economic value added (EVA)**      | Profits beyond what is necessary for investors                                                      | @sec-Pricing                                    |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Equal Priority**                  | Rule for distributing funds among claimants                                                         | @sec-Complications                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Expected loss share**             | a unit's share of a layer expected loss, $\alpha_k^i$                                               | @sec-Allocating-Capital                         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Funding equation**                | states that assets are the sum of premiums and investor capital, $a=P+Q$                            | @eq-funding, @sec-Intro-Insco                   |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Gradient**                        | derivative with respect to several variables                                                        | @sec-Risk-Analysis                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **InsCo**                           | hypothetical insurer used as a simple example                                                       | @sec-Intro-Insco                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Insureds**                        | customers of InsCo, who pay premiums                                                                | @sec-Intro-Insco                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Investors**                       | owners of InsCo, who supply capital                                                                 | @sec-Intro-Insco                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Law invariance**                  | risk measure depends only on distribution                                                           | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Layer**                           | segment of assets between two levels of portfolio loss                                              | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Layer funding equation**          | states that layer assets are the sum of premiums and investor capital, $\Delta X_k=P_k+Q_k$         | @eq-layer-funding, @sec-Pricing-layers          |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Likelihood ratio**                | ratio of distorted to original probabilities                                                        | @sec-pricing-events                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Margin**                          | difference between premium and expected loss, $M=P-L$                                               | @eq-PLM, @sec-Pricing                           |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Marginal approach**               | examine the effect of a small change; look at first derivative                                      | @sec-Risk-Analysis                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Model**                           | simplified representation of reality, usually mathematical                                          | @sec-What-Into, @sec-System-Overview            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Natural Allocation (NA)**         | decomposition of portfolio premium into distorted expectation of unit losses                        | @sec-pricing-units                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Natural Allocation of capital**   | allocation of capital consistent with allocation of premium, $Q_k^i$                                | @sec-Allocating-Capital                         |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Normal copula**                   | multivariate uniform distribution based on the normal                                               | @sec-IC-NC                                      |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Objectivity**                     | synonym for law invariance                                                                          | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Parameter uncertainty**           | lack of knowledge about parameters of a process, sometimes modeled as a distribution                | @sec-Uncertainty                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Pricing**                         | module assigns technical premium to the portfolio           | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Pricing & Allocation**            | module that assigns technical premiums to units                                                     | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Pricing risk measure**            | rule that relates liabilities to technical premiums                                                 | @sec-Intro-Insco                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Pro forma**                       | hypothetical financial statement                                                                    | @sec-System-Overview , @sec-BO-Pro-Forma        |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Proxy model**                     | simpler model of another model                                                                      | @sec-portfolio-optimization                     |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Probabilistic database**          | stored sample of random outcomes                                                                    | @sec-BO-Units                                   |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Process risk**                    | randomness in outcomes from a well defined and parameterized stochastic process                     | @sec-Uncertainty                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Reinsurance**                     | module that deals with risk transfer                                                                | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Risk appetite**                   | compensation/price limit for taking on risk                                                         | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Risk tolerance**                  | limit of risk the firm is willing to take on                                                        | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **RVaR**                            | Range Value at Risk, window version of VaR                                                          | @sec-Risk-Analysis                              |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Quantity of Interest**            | target metric, statistic, etc., of a simulation exercise                                            | @sec-Uncertainty                                |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Spectral risk measure (SRM)**     | risk measure determined by a distortion function                                                    | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **State price**                     | A contract that pays \$1 in a particular state of the world                                         | @sec-pricing-events                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Tranche**                         | synonym for layer                                                                                   | @sec-Pricing-layers                             |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Unit**                            | portion of portfolio, e.g., line of business                                                        | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Value at Risk (VaR)**             | risk measure, quantile of a distribution                                                            | @sec-System-Overview                            |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Tail Value at Risk (TVaR)**       | average of losses in a specified tail probability; also CVaR, TCE                                   | @sec-Capital-Adequacy                           |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+
| **Excess TVaR (XTVaR)**             | TVaR minus expected losses                                                                          | @sec-ISA                                        |
+-------------------------------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------+

\normalsize

\clearpage
